# Generated by Django 5.0.2 on 2024-02-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(default='NULL', max_length=12)),
                ('tag', models.CharField(default='NULL', max_length=10)),
                ('category', models.CharField(default='Finished', max_length=30)),
                ('stock', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('available_stock', models.IntegerField(default=0)),
            ],
        ),
    ]
