# Generated by Django 5.0.2 on 2024-02-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='available_stock',
            new_name='availableStock',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='stock',
            new_name='currentStock',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
