# Generated by Django 5.0.2 on 2024-02-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_api', '0002_category_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
