# Generated by Django 5.0.2 on 2024-02-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_api', '0004_item_category_alter_item_availablestock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
